language: python
python:
  - 2.6
  - 2.7
  - 3.4
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
install:
  - npm install -G socket.io
  - npm install -G yargs
  - pip install -U requests
  - pip install -U six
  - pip install -U websocket-client
  - pip install -U coverage
before_script:
  - DEBUG=* node socketIO_client/tests/serve.js &
  - sleep 3
script: nosetests
