language: cpp
sudo: required

cache:
  directories:
    - $HOME/opt

addons:
  coverity_scan:
    project:
      name: "diydrones/ardupilot"
      description: "Build submitted via Travis CI"
    notification_email: andrew-scan@tridgell.net
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: coverity_scan

before_install:
  - export PATH=$(echo ${PATH} | awk -v RS=':' -v ORS=':' '/clang/ {next} {print}' | sed 's/:*$//')
  - APMDIR=$(pwd) && pushd .. && $APMDIR/Tools/scripts/configure-ci.sh && . ~/.profile && popd

script:
  - python Tools/autotest/param_metadata/param_parse.py
  - Tools/scripts/build_ci.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e5e0b55e353e53945b4b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

compiler: gcc

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "FjIwqZQV2FhNPWYITX5LZXTE38yYqBaQdbm3QmbEg/30wnPTm1ZOLIU7o/aSvX615ImR8kHoryvFPDQDWc6wWfqTEs3Ytq2kIvcIJS2Y5l/0PFfpWJoH5gRd6hDThnoi+1oVMLvj1+bhn4yFlCCQ2vT/jxoGfiQqqgvHtv4fLzI="
  matrix:
    - CI_BUILD_TARGET="px4-v2 px4-v4"
    - CI_BUILD_TARGET="sitl linux minlure"
    - CI_BUILD_TARGET="navio raspilot bebop"
    - CI_BUILD_TARGET="sitltest"

matrix:
  include:
    - compiler: clang
      env: CI_BUILD_TARGET="sitl linux minlure"
    - compiler: clang
      env: CI_BUILD_TARGET="navio raspilot bebop"